### ISSUE TITLE
Learning Resources

### ISSUE THREAD

**Issue by ghost** [gebo96/samp-gamemode#1]
I'm extremely sorry because this is not an issue. Actually, I want to learn SA-MP scripting, but the official documentation and forum has been removed. Can anyone mention any place where I can find those

**Comment by german-schneck** [comment]
Hello! Don't worry. They have mirrored the documentation here https://sampwiki.blast.hk/wiki/Main_Page

I am sure that in the future there will be more websites

I am not involved in the SAMP world anymore but I hope this helps you.

Good luck!
